### ISSUE TITLE
WCF and EF Core

### ISSUE THREAD

**Issue by LucaGabi** [azabluda/InfoCarrier.Core#1]
Hi,

    Can this be deployed to a linux machine ? Is it tied to WCF ?

**Comment by azabluda** [comment]
Hi @LucaGabi, thank you for your interest!

No, InfoCarrier.Core is not tied to WCF. You are free to choose the communication framework which suits your needs best, such as ASP.NET Core or ServiceStack (both should work on Linux). You can check the relevant sample applications in the [/sample](https://github.com/azabluda/InfoCarrier.Core/tree/develop/sample) folder.
