### ISSUE TITLE
Memorys leak in EF Core execution plan cache

### ISSUE THREAD

**Issue by vluedeling** [azabluda/InfoCarrier.Core#3]
Hello Alexander,
we have identified a memory leak in our deployment of InfoCarrier Core. We have a WPF client which sends queries to the InfoCarrier server, which in turn queries an SQL server database through Entity Framework Core. We use your InfoCarrier Core framework in version 2.2.6.

We have, since recently, a query which is executed every 5 seconds. In the server, we notice a steady increase in memory consumption whenever clients are connected.

We have narrowed the problem down to the usage of anonymous types ("new { ... }") in the query, like so:
```
                    var maxTimes = dbContext.Set<EventCapture>()
                        .GroupBy(
                            x => x.MachineId,
                            (x, y) => new { MachineId = x, MaxTime = y.Max(a => a.Timestamp) })
                        .Select(x => new EventCapture() { MachineId = x.MachineId, Timestamp = x.MaxTime })
                        .ToList();
``````
The profiler shows that Entity Framework Core creates new Cache Entries for the execution plans in every request, which is only supposed to happen once per distinct statement. Those plans remain in the cache and are never purged.

Your QueryDataHelper instantiates a new TypeResolver on every request, which causes the Aqua TypeSystem to always create new Runtime Types, which in turn make EF Core think that it has encountered a new type of query.

We could solve the issue with a rather straightforward change. Instead of having the QueryDataHelper create a new TypeResolver on every request, we use the static instance field provided by the TypeResolver. This makes the memory leak disappear (and also increases performance for client requests).

I suspect that this problem will also arise in the current version of InfoCarrier Core, because it also uses new TypeResolver instances for requests.

I will upload our my proposed change as a pull request.

Regards,

Volker

**Comment by vluedeling** [comment]
See pull request #4

**Comment by azabluda** [comment]
Hi Volker, the PR looks good now. I'm gonna merge it and release the nugets for 2.x and 3.x later today. Thanks a lot for your contribution. Take care 👋

**Comment by azabluda** [comment]
Service releases:
- https://www.nuget.org/packages/InfoCarrier.Core/2.2.7
- https://www.nuget.org/packages/InfoCarrier.Core/3.1.1
